---
abstract: 'a script tag with javascript code supplied via field for HTML::FormHandler.'
author:
  - 'Charlie Garrison <garrison@zeta.org.au>'
build_requires:
  HTML::FormHandler: '0'
  HTML::FormHandler::Moose: '0'
  Test::JSON: '0'
  Test::JavaScript: '0'
  Test::More: '0'
  strict: '0'
  utf8: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: HTML-FormHandlerX-Field-JavaScript
requires:
  HTML::FormHandler::Field::NoValue: '0'
  JSON::MaybeXS: '0'
  JavaScript::Minifier::XS: '0'
  Moose: '0'
  namespace::autoclean: '0'
  perl: '5.010'
resources:
  bugtracker: https://github.com/cngarrison/HTML-FormHandlerX-Field-JavaScript/issues
  homepage: https://github.com/cngarrison/HTML-FormHandlerX-Field-JavaScript
  repository: https://github.com/cngarrison/HTML-FormHandlerX-Field-JavaScript.git
version: '0.003'
